# Generated by Django 4.0.7 on 2022-09-26 08:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='image',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='feature_image',
            field=models.ForeignKey(blank=True, help_text='Select an image to feature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('highlight_block', wagtail.blocks.StructBlock([('format', wagtail.blocks.ChoiceBlock(blank=True, choices=[('normal', 'regular'), ('font-style : italic;', 'italic'), ('font-weight: bold;', 'bold'), ('font-style : italic; font-weight: bold;', 'bold-italic')])), ('highlight_items', wagtail.blocks.StreamBlock([('text', wagtail.blocks.ListBlock(blank=True, child_block=wagtail.blocks.CharBlock(max_length=512), required=True))]))])), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL like a video from Youtube.', icon='fa-s15', template='blocks/embed_block.html')), ('two_column_block', wagtail.blocks.StreamBlock([('paragraph_block', wagtail.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL like a video from Youtube.', icon='fa-s15', template='blocks/embed_block.html'))], max_num=2, min_num=2))], blank=True, help_text='Feeling creative? Word up and paint a better picture.', use_json_field=True, verbose_name='Page body'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe this page'),
        ),
    ]
