# Generated by Django 4.0.7 on 2022-09-24 03:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('personnel', '0001_initial'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdatepersonnelrelationship',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_projectupdate_relationship', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='projectupdatepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='bulletin.projectupdatepage'),
        ),
        migrations.AddField(
            model_name='projectupdatepagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='projectupdatepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='bulletin.ProjectUpdatePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='bulletinboard',
            name='feature_image',
            field=models.ForeignKey(blank=True, help_text='This image will be used when this page is shared or embedded in another page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='feature image'),
        ),
        migrations.AddField(
            model_name='bulletinboard',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='hero image'),
        ),
    ]
